export const walletMultiButtonCustomStyles = {
  display: "inline-flex",
  alignItems: "center",
  justifyContent: "center",
  gap: "0.5rem",
  whiteSpace: "nowrap",
  borderRadius: "0.375rem",
  fontSize: "0.875rem",
  fontWeight: "500",
  height: "2.5rem",
  padding: "0.5rem 1rem",
  backgroundColor: "hsl(var(--primary))",
  color: "hsl(var(--primary-foreground))",
  transition: "background-color 150ms cubic-bezier(0.4, 0, 0.2, 1)",
  cursor: "pointer",
  border: "none",
  outline: "none",
  position: "relative",
} as const;
